### ISSUE TITLE
pyads on PyPI

### ISSUE THREAD

**Issue by ccatterina** [chwiede/pyads#13]
Hi @chwiede, can you please submit pyads to PyPI?
Thanks

**Comment by chwiede** [comment]
I'll try it... 

Hint:
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by bfabio** [comment]
@chwiede Any news on this?

**Comment by chwiede** [comment]
Yeah, i've got a login to pypi now ;-) Just kidding, i'm very busy at the moment - sorry for that.
I'm on it now.

**Comment by chwiede** [comment]
Setup.py and package created. Can't upload it, maybe a wrong config on my system. I've to look for this.

**Comment by chwiede** [comment]
Uploaded to test repo: https://testpypi.python.org/pypi?:action=display&name=pyads&version=0.1.1

Any volunteers for testing it?

**Comment by chwiede** [comment]
Well, someone was faster than me: https://pypi.python.org/pypi/pyads/2.2.0
How to deal with that? I guess i need another name for this package?

**Comment by bfabio** [comment]
> Uploaded to test repo: https://testpypi.python.org/pypi?:action=display&name=pyads&version=0.1.1
> Any volunteers for testing it?

Great! I will be testing it ASAP.

> Well, someone was faster than me: https://pypi.python.org/pypi/pyads/2.2.0
> How to deal with that? I guess i need another name for this package?

Yeah, pypi has a first come first served approach when it comes to package names. I think `chwiede.pyads` would be a fine second choice.

**Comment by bfabio** [comment]
> Any volunteers for testing it?

It works with both pip2 and pip3 when installing from testpypi.
