### ISSUE TITLE
Create route from PLC to laptop directly from Linux (Ubuntu 16.04)

### ISSUE THREAD

**Issue by sebastianbk** [chwiede/pyads#17]
Hi,

First of all, thank you for sharing this amazing project. :+1: 

I have been using your package successfully in Ubuntu 16.04 and I have managed to both read and write variables to my Beckhoff CX9020 via ADS. However, I have had to create a route from the PLC to my laptop using the TwinCAT Router UI in Windows before being able to interact with the PLC in Ubuntu.

Is there any way I can log into the PLC and add the route directly in Ubuntu using Python?

I hope there is and that you can point me in the direction of a solution. :blush:

**Comment by chwiede** [comment]
Hello,

unfortunately i've no idea how to implement this - so at the moment Windows is the only choice if a route is needed.

https://github.com/MrLeeh/pyads could be an alternative.
