### ISSUE TITLE
Beckhoff AMS MESSAGE

### ISSUE THREAD

**Issue by salwaalem** [chwiede/pyads#21]
Hi,

I'm working with Beckhoff automaton and I'm looking a way to capture its sys logs and AMS messages. 

Any ideas please ?

**Comment by chwiede** [comment]
Hi,

there's no special support to do this. Have a look here: https://infosys.beckhoff.com/english.php?content=../content/1033/tcadsdeviceplc/html/tcadsdeviceplc_indexadsservice.htm&id=

Maybe you find something helpful there to get your information via ADS. 

Capturing AMS messages can be done with wireshark or similar tools.
