### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by mttmnr** [chwiede/pyads#4]
Hi! 
I'm quite new to Beckhoff and ADS; i'm trying to use your code to connect from a python client, but it is not clear to me what exactly should I do to "insert your client AMS-ID into the ams table of your target device! "
can you explain it more 'operativly'?

Thank you in advance
Matteo

**Comment by chwiede** [comment]
Hi Matteo, 

each ADS Device (sps, coupler, etc) has a "ADS Table". Each ADS-Client has an AMS-ID. If this AMS-ID isn't listed in the target devices table, it won't be allowed to access.

This ams table might be empty, in this case any client is allowed - give it a try.

While using pyads the clients ams-id is defined by you.

For 'operativly' informations you have to consult your manual - a sps or emulated sps work's different then a bus coupler.

Good luck,
Christoph

**Comment by mttmnr** [comment]
Thanks
I'm trying to connect from python to a Beckhoff Twincat 3 system, so i was
wondering where the table is ( maybe i have to create the route); i will
search better: from what I see , beckhoff Infosys is full of informations,
but not always easy to find.

Thanks a lot !
Matteo




2015-11-19 18:14 GMT+01:00 Christoph Wiedemann <notifications@github.com>:
